<?php $title='Store'; ob_start(); ?>
<style>.store-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr),);gap:20px}.store-card{background:#12161b;border:1px solid #252a31;box-shadow:0 12px 30px rgba(0,0,0,.25);display:flex;flex-direction:column;min-height:100%}.store-card-image{height:190px;background:#0b0e12;display:flex;align-items:center;justify-content:center;overflow:hidden;border-bottom:1px solid #252a31}.store-card-image img{width:100%;height:100%;object-fit:cover}.store-card-body{padding:20px;display:flex;flex-direction:column;flex:1}.store-card h2{margin:4px 0 10px;color:#f4f6f8}.store-card p{color:#9da4ad;flex:1}.store-category{text-transform:uppercase;letter-spacing:.12em;font-size:10px;color:#c4312e;font-weight:bold}.store-card-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:18px;padding-top:15px;border-top:1px solid #252a31}.store-card-footer strong{font-size:18px;color:#f4f6f8}.paypal-wrap{margin-top:14px}.paypal-status{font-size:12px;margin-top:8px;color:#8b929c}.paypal-status.error{color:#ef443f}.paypal-status.success{color:#7ddc9a}paypal-button{display:block}</style>
<section class="portal-section"><div class="panel-title"><div><h1>Aera Store</h1><p class="muted">Support Aera and receive your in-game rewards automatically after PayPal confirms payment.</p></div></div>
<?php if(!$products): ?><div class="panel"><h2>Store coming soon</h2><p class="muted">There are no store products available yet. Check back soon.</p></div>
<?php else: ?><div class="store-grid"><?php foreach($products as $p): $paid=((float)$p['Price']>0); ?><article class="store-card"><?php if(!empty($p['ImageURL'])): ?><div class="store-card-image"><img src="<?= e($p['ImageURL']) ?>" alt="<?= e($p['Title']) ?>" loading="lazy"></div><?php endif; ?><div class="store-card-body"><?php if(!empty($p['Category'])): ?><div class="store-category"><?= e($p['Category']) ?></div><?php endif; ?><h2><?= e($p['Title']) ?></h2><?php if(!empty($p['Description'])): ?><p><?= nl2br(e($p['Description'])) ?></p><?php endif; ?><div class="store-card-footer"><strong><?= e($p['Currency']) ?> <?= number_format((float)$p['Price'],2) ?></strong></div>
<?php if(!$user): ?><div class="paypal-wrap"><a class="btn btn-gold" href="/login">Sign in to purchase</a></div>
<?php elseif(!$paid): ?><div class="paypal-status">Coming soon</div>
<?php elseif(!empty($p['PurchaseURL'])): ?><div class="paypal-wrap"><a class="btn btn-gold" href="<?= e($p['PurchaseURL']) ?>" target="_blank" rel="noopener">Purchase</a></div>
<?php else: ?><div class="paypal-wrap"><paypal-button id="paypal-btn-<?= (int)$p['id'] ?>" type="pay" hidden data-currency="<?= e(strtoupper((string)$p['Currency'])) ?>"></paypal-button><div class="paypal-status" id="paypal-status-<?= (int)$p['id'] ?>">Loading PayPal…</div></div><?php endif; ?></div></article><?php endforeach; ?></div><?php endif; ?></section>
<?php if($user && $products): ?><script>
const aeraCsrf=<?= json_encode((string)\Aera\Foundation\Csrf::token()) ?>;
async function aeraJsonResponse(response){const text=await response.text();let data=null;try{data=JSON.parse(text)}catch(e){throw new Error('PayPal configuration request returned HTML instead of JSON (HTTP '+response.status+'). Check the Aera API route and IIS rewrite rules.')}if(!response.ok)throw new Error(data?.error||('Request failed (HTTP '+response.status+').'));return data}
async function aeraFetch(u,o={}){o.headers=Object.assign({'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},o.headers||{});return fetch(u,o)}
async function aeraCreateOrder(id){const d=await aeraJsonResponse(await aeraFetch('/api/store/paypal/create-order',{method:'POST',body:new URLSearchParams({_token:aeraCsrf,productId:String(id)})}));if(!d.id)throw new Error(d.error||'Unable to create PayPal order.');return d.id}
async function aeraCapture(id){const d=await aeraJsonResponse(await aeraFetch('/api/store/paypal/'+encodeURIComponent(id)+'/capture',{method:'POST',body:new URLSearchParams({_token:aeraCsrf})}));if(!d.success)throw new Error(d.error||'Payment capture failed.');return d}
async function aeraPayPalLoaded(){try{if(!window.paypal)throw new Error('PayPal SDK did not load.');const cfg=await aeraJsonResponse(await fetch('/api/store/paypal/client-config',{cache:'no-store',headers:{'Accept':'application/json'}}));if(!cfg.clientId)throw new Error('PayPal Client ID is not configured.');const sdk=await window.paypal.createInstance({clientId:cfg.clientId,components:['paypal-payments'],pageType:'checkout'});for(const el of document.querySelectorAll('paypal-button[id^="paypal-btn-"]')){const id=parseInt(el.id.replace('paypal-btn-',''),10),currency=(el.dataset.currency||'USD').toUpperCase(),status=document.getElementById('paypal-status-'+id);const methods=await sdk.findEligibleMethods({currencyCode:currency});if(!methods.isEligible('paypal')){status.textContent='PayPal is not available for this currency/account.';status.className='paypal-status error';continue;}const session=sdk.createPayPalOneTimePaymentSession({onApprove:async({orderId})=>{try{status.textContent='Confirming payment…';await aeraCapture(orderId);status.textContent='Payment complete — your items and titles have been added to your account.';status.className='paypal-status success'}catch(e){status.textContent=e.message||'Payment capture failed.';status.className='paypal-status error'}},onCancel:()=>status.textContent='Payment cancelled.',onError:e=>{console.error(e);status.textContent='PayPal encountered an error. Please try again.';status.className='paypal-status error'}});el.removeAttribute('hidden');status.textContent='';el.addEventListener('click',async()=>{try{status.textContent='Opening PayPal…';await session.start({presentationMode:'auto'},aeraCreateOrder(id))}catch(e){console.error(e);status.textContent=e.message||'Unable to start PayPal.';status.className='paypal-status error'}})}}catch(e){console.error(e);for(const s of document.querySelectorAll('.paypal-status')){s.textContent=e.message||'PayPal is unavailable.';s.className='paypal-status error'}}}
</script><script src="<?= $paypalMode==='live'?'https://www.paypal.com/web-sdk/v6/core':'https://www.sandbox.paypal.com/web-sdk/v6/core' ?>" onload="aeraPayPalLoaded()"></script><?php endif; ?>
<?php $content=ob_get_clean(); require __DIR__.'/layouts/site.php'; ?>
