<?php $title='Store'; $heading=$mode==='edit'?'Edit Product':'Add Product'; $subheading='Configure the product and the game rewards granted after confirmed payment.'; $itemRewards=[]; $titleRewards=[]; foreach(($rewards??[]) as $r){ if($r['RewardType']==='item')$itemRewards[]=$r; else $titleRewards[]=$r; } ob_start(); ?>
<div class="panel-title"><div><h2><?= $mode==='edit'?'Edit Product':'Add Product' ?></h2><p class="muted">Attach any number of existing items and titles. Rewards are granted only after a verified PayPal capture.</p></div><a class="btn btn-ghost" href="/admin/store">Back to Store</a></div>
<div class="panel"><form method="post" action="<?= $mode==='edit'?'/admin/store/'.(int)$product['id'].'/edit':'/admin/store/new' ?>">
<?= csrf_field() ?>
<div class="form-grid">
<label>Title<input type="text" name="Title" maxlength="150" required value="<?= e((string)($product['Title']??'')) ?>"></label>
<label>Category<input type="text" name="Category" maxlength="80" placeholder="Cosmetics, Supporter, Upgrade..." value="<?= e((string)($product['Category']??'')) ?>"></label>
<label>Price<input type="number" name="Price" min="0" step="0.01" value="<?= e((string)($product['Price']??'0.00')) ?>"></label>
<label>Currency<input type="text" name="Currency" maxlength="10" value="<?= e((string)($product['Currency']??'USD')) ?>"></label>
<label>Sort Order<input type="number" name="SortOrder" value="<?= e((string)($product['SortOrder']??0)) ?>"></label>
<label>Image URL<input type="url" name="ImageURL" maxlength="1000" placeholder="https://..." value="<?= e((string)($product['ImageURL']??'')) ?>"></label>
<label class="form-full">Purchase URL<input type="url" name="PurchaseURL" maxlength="1000" value="<?= e((string)($product['PurchaseURL']??'')) ?>"><small class="muted">Leave blank when this product uses the site's PayPal Checkout.</small></label>
<label class="form-full">Description<textarea name="Description" rows="6" maxlength="5000"><?= e((string)($product['Description']??'')) ?></textarea></label>
</div>
<div class="panel" style="margin-top:20px;background:rgba(255,255,255,.025)"><div class="panel-title"><div><h3>Item Rewards</h3><p class="muted">Adds the selected item quantities to the buyer's normal inventory.</p></div><button class="btn btn-ghost" type="button" onclick="addItemReward()">Add Item</button></div>
<div id="items-rewards"><?php if(!$itemRewards): ?><div class="reward-empty muted">No item rewards configured.</div><?php endif; ?><?php foreach($itemRewards as $r): ?><div class="reward-row" style="display:flex;gap:10px;align-items:end;margin-bottom:10px"><label style="flex:1">Item<select name="ItemIDs[]"><option value="">Select item</option><?php foreach(($items??[]) as $item): ?><option value="<?= (int)$item['id'] ?>" <?= (int)$item['id']===(int)$r['RewardID']?'selected':'' ?>>#<?= (int)$item['id'] ?> — <?= e((string)$item['Name']) ?><?= !empty($item['Equipment'])?' · '.e((string)$item['Equipment']):'' ?></option><?php endforeach; ?></select></label><label style="width:130px">Quantity<input type="number" min="1" max="9999" name="ItemQty[]" value="<?= (int)$r['Quantity'] ?>"></label><button class="btn btn-danger" type="button" onclick="this.parentElement.remove()">Remove</button></div><?php endforeach; ?></div></div>
<div class="panel" style="margin-top:20px;background:rgba(255,255,255,.025)"><div class="panel-title"><div><h3>Title Rewards</h3><p class="muted">Adds the selected title to the buyer's account, once.</p></div><button class="btn btn-ghost" type="button" onclick="addTitleReward()">Add Title</button></div>
<div id="title-rewards"><?php if(!$titleRewards): ?><div class="reward-empty muted">No title rewards configured.</div><?php endif; ?><?php foreach($titleRewards as $r): ?><div class="reward-row" style="display:flex;gap:10px;align-items:end;margin-bottom:10px"><label style="flex:1">Title<select name="TitleIDs[]"><option value="">Select title</option><?php foreach(($titles??[]) as $item): ?><option value="<?= (int)$item['id'] ?>" <?= (int)$item['id']===(int)$r['RewardID']?'selected':'' ?>>#<?= (int)$item['id'] ?> — <?= e((string)$item['Name']) ?></option><?php endforeach; ?></select></label><button class="btn btn-danger" type="button" onclick="this.parentElement.remove()">Remove</button></div><?php endforeach; ?></div></div>
<label class="check-row" style="margin-top:20px"><input type="checkbox" name="Active" value="1" <?= !isset($product['Active'])||$product['Active']?'checked':'' ?>> Active on public Store</label>
<div style="margin-top:20px"><button class="btn btn-gold" type="submit">Save Product</button></div>
</form></div>
<script>
const itemOptions=<?= json_encode($items??[],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;const titleOptions=<?= json_encode($titles??[],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function addItemReward(){const w=document.getElementById('items-rewards');const e=w.querySelector('.reward-empty');if(e)e.remove();const r=document.createElement('div');r.className='reward-row';r.style='display:flex;gap:10px;align-items:end;margin-bottom:10px';r.innerHTML='<label style="flex:1">Item<select name="ItemIDs[]"><option value="">Select item</option>'+itemOptions.map(x=>'<option value="'+x.id+'">#'+x.id+' — '+esc(x.Name)+(x.Equipment?' · '+esc(x.Equipment):'')+'</option>').join('')+'</select></label><label style="width:130px">Quantity<input type="number" min="1" max="9999" name="ItemQty[]" value="1"></label><button class="btn btn-danger" type="button" onclick="this.parentElement.remove()">Remove</button>';w.appendChild(r);}
function addTitleReward(){const w=document.getElementById('title-rewards');const e=w.querySelector('.reward-empty');if(e)e.remove();const r=document.createElement('div');r.className='reward-row';r.style='display:flex;gap:10px;align-items:end;margin-bottom:10px';r.innerHTML='<label style="flex:1">Title<select name="TitleIDs[]"><option value="">Select title</option>'+titleOptions.map(x=>'<option value="'+x.id+'">#'+x.id+' — '+esc(x.Name)+'</option>').join('')+'</select></label><button class="btn btn-danger" type="button" onclick="this.parentElement.remove()">Remove</button>';w.appendChild(r);}
</script>
<?php $content=ob_get_clean(); require __DIR__.'/../../layouts/admin.php'; ?>
