<?php
declare(strict_types=1);
namespace AeraEmu;

use Throwable;

/** Java World.retrieveDatabaseObject() cache layer, ported for the PHP daemon. */
final class WorldRepository
{
    public array $maps=[],$monsters=[],$skills=[],$rates=[],$filters=[],$server=[],$settings=[];
    public array $items=[],$quests=[],$shops=[],$achievements=[],$auras=[],$auraEffects=[],$enhancements=[],$patterns=[],$factions=[],$titles=[],$globalDrops=[],$hairshops=[],$hairs=[],$seasonalShops=[],$wheels=[],$serverMessages=[];
    public array $npcs=[],$npcButtons=[],$mapNpcRows=[],$mapArrowRows=[];
    public array $skillsAuras=[],$specialSkills=[],$mapMonsterRows=[],$monsterSkills=[],$auraEffectsByAura=[];
    public array $itemRequirements=[],$classes=[],$classSkills=[],$mapItems=[],$monsterDrops=[],$questRequiredItems=[],$questRequirements=[],$questRewards=[],$shopItems=[],$hairshopItems=[];
    public string $newsString='';
    /** Runtime Java World EXP/CP/GOLD/COINS/REP/DROP rate multipliers. */
    public array $rewardRates=['exp'=>1,'cp'=>1,'gold'=>1,'coins'=>1,'rep'=>1,'drop'=>0];
    private string $serverName;

    public function __construct(private Database $db,string $serverName='Aera',private ?Logger $log=null){ $this->serverName=$serverName;$this->reload(); }
    public function setServerName(string $name): void { $this->serverName=$name; }

    public function reload(): void
    {
        $this->maps=$this->keyed('SELECT * FROM maps',fn($r)=>strtolower((string)$r['Name']));
        $this->items=$this->keyed('SELECT * FROM items WHERE id>0',fn($r)=>(int)$r['id']);
        $this->monsters=$this->keyed('SELECT * FROM monsters',fn($r)=>(int)$r['id']);
        $this->skills=$this->keyed('SELECT * FROM skills',fn($r)=>(int)$r['id']);
        $this->quests=$this->keyed('SELECT * FROM quests',fn($r)=>(int)$r['id']);
        $this->shops=$this->keyed('SELECT * FROM shops',fn($r)=>(int)$r['id']);
        $this->achievements=$this->keyed('SELECT * FROM achievements',fn($r)=>(int)$r['id']);
        $this->auras=$this->keyed('SELECT * FROM auras WHERE id>0',fn($r)=>(int)$r['id']);
        $this->auraEffects=$this->keyed('SELECT * FROM auras_effects',fn($r)=>(int)$r['id']);
        $this->auraEffectsByAura=[];foreach($this->auraEffects as $e)$this->auraEffectsByAura[(int)$e['AuraID']][]=$e;
        $this->enhancements=$this->keyed('SELECT * FROM enhancements',fn($r)=>(int)$r['id']);
        $this->patterns=$this->keyed('SELECT * FROM enhancements_patterns WHERE id>0',fn($r)=>(int)$r['id']);
        $this->factions=$this->keyed('SELECT * FROM factions',fn($r)=>(int)$r['id']);
        $this->titles=$this->keyed('SELECT * FROM titles WHERE id>0',fn($r)=>(int)$r['id']);
        $this->globalDrops=$this->keyed('SELECT * FROM global_drops',fn($r)=>(int)$r['id']);
        $this->hairs=$this->keyed('SELECT * FROM hairs',fn($r)=>(int)$r['id']);
        $this->hairshops=$this->keyed('SELECT * FROM hairs_shops',fn($r)=>(int)$r['id']);
        $this->seasonalShops=$this->rows('SELECT * FROM shops_seasonal');
        $this->wheels=$this->keyed('SELECT * FROM wheels',fn($r)=>(int)$r['ItemID']);
        $this->serverMessages=$this->keyed('SELECT * FROM settings_messages',fn($r)=>(int)$r['id']);

        // Database-driven NPCs (Aera v30.20). Support both the current
        // maps_npc name and the older maps_npcs schema used by legacy servers.
        $this->npcs=$this->db->tableExists('npcs')?$this->keyed('SELECT * FROM npcs',fn($r)=>(int)$r['id']):[];
        $this->npcButtons=[];
        if($this->db->tableExists('npcs_buttons'))foreach($this->rows('SELECT * FROM npcs_buttons ORDER BY NPCID,id') as $r)$this->npcButtons[(int)$r['NPCID']][]=$r;
        $this->mapNpcRows=[];
        // Merge legacy maps_npcs first, then current maps_npc so current rows win
        // only when both schemas contain the same map instance id.
        foreach(['maps_npcs','maps_npc'] as $npcMapTable){
            if(!$this->db->tableExists($npcMapTable))continue;
            foreach($this->rows("SELECT * FROM `{$npcMapTable}` ORDER BY MapID,NpcMapID,id") as $r){$mapId=(int)($r['MapID']??0);$npcMapId=(int)($r['NpcMapID']??0);if($npcMapId<=0)$npcMapId=(int)($r['id']??0);$r['NpcMapID']=$npcMapId;$this->mapNpcRows[$mapId][$npcMapId]=$r;}
        }


        // Database-driven map arrows (Aera v30.38). These are visual walk-over
        // transition controls generated by the client after a map has loaded.
        $this->mapArrowRows=[];
        if($this->db->tableExists('maps_arrows')){
            foreach($this->rows('SELECT * FROM maps_arrows WHERE Enabled=1 ORDER BY MapID,Frame,id') as $r){
                $mapId=(int)($r['MapID']??0);if($mapId>0)$this->mapArrowRows[$mapId][]=$r;
            }
        }

        $this->mapMonsterRows=[];
        foreach($this->rows('SELECT mm.*,m.Name MonsterName FROM maps_monsters mm INNER JOIN monsters m ON m.id=mm.MonsterID ORDER BY mm.MapID,mm.MonMapID') as $r){
            if(array_key_exists('Enabled',$r) && (int)$r['Enabled']===0)continue;
            $this->mapMonsterRows[(int)$r['MapID']][(int)$r['MonMapID']]=$r;
        }
        $this->skillsAuras=[];foreach($this->rows('SELECT SkillID,AuraID FROM skills_auras ORDER BY id') as $r)$this->skillsAuras[(int)$r['SkillID']][]=(int)$r['AuraID'];
        $this->specialSkills=[];foreach($this->rows('SELECT ItemID,SkillID FROM items_skills') as $r)$this->specialSkills[(int)$r['ItemID']]=(int)$r['SkillID'];
        $this->monsterSkills=[];foreach($this->rows('SELECT MonsterID,SkillID FROM monsters_skills ORDER BY MonsterID') as $r)$this->monsterSkills[(int)$r['MonsterID']][]=(int)$r['SkillID'];
        // Java World.retrieveDatabaseObject() also materializes all child collections.
        $this->itemRequirements=[];foreach($this->rows('SELECT * FROM items_requirements ORDER BY id') as $r)$this->itemRequirements[(int)$r['ItemID']][]=$r;
        $this->classes=$this->keyed('SELECT * FROM classes',fn($r)=>(int)$r['ItemID']);
        $this->classSkills=[];foreach($this->rows('SELECT * FROM skills_assign ORDER BY id') as $r)$this->classSkills[(int)$r['ItemID']][]=(int)$r['SkillID'];
        $this->mapItems=[];foreach($this->rows('SELECT * FROM maps_items ORDER BY MapID,ItemID') as $r)$this->mapItems[(int)$r['MapID']][]=$r;
        $this->monsterDrops=[];foreach($this->rows('SELECT * FROM monsters_drops ORDER BY id') as $r)$this->monsterDrops[(int)$r['MonsterID']][]=$r;
        $this->questRequiredItems=[];foreach($this->rows('SELECT * FROM quests_required_items ORDER BY id') as $r)$this->questRequiredItems[(int)$r['QuestID']][]=$r;
        $this->questRequirements=[];foreach($this->rows('SELECT * FROM quests_requirements ORDER BY id') as $r)$this->questRequirements[(int)$r['QuestID']][]=$r;
        $this->questRewards=[];foreach($this->rows('SELECT * FROM quests_rewards ORDER BY id') as $r)$this->questRewards[(int)$r['QuestID']][]=$r;
        $this->shopItems=[];foreach($this->rows('SELECT * FROM shops_items ORDER BY id') as $r)$this->shopItems[(int)$r['ShopID']][]=$r;
        $this->hairshopItems=[];foreach($this->rows('SELECT * FROM hairs_shops_items ORDER BY ShopID') as $r)$this->hairshopItems[(int)$r['ShopID']][]=$r;
        $this->rates=[];foreach($this->rows('SELECT name,value FROM settings_rates') as $r)$this->rates[(string)$r['name']]=is_numeric($r['value'])?(float)$r['value']:$r['value'];
        $this->filters=[];foreach($this->rows('SELECT * FROM settings_filters') as $r){$word=trim((string)($r['Word']??$r['word']??''));if($word!=='')$this->filters[strtolower($word)]=(int)($r['Mutetime']??$r['mutetime']??5);}
        $this->server=$this->db->one('SELECT * FROM servers WHERE Name=? LIMIT 1',[$this->serverName])??$this->db->one('SELECT * FROM servers ORDER BY id LIMIT 1')??[];
        $this->settings=$this->rows('SELECT * FROM settings_login ORDER BY id');
        $pairs=[];foreach($this->settings as $r){$pairs[]=(string)($r['name']??'').'='.(string)($r['value']??'');}$this->newsString=implode(',',$pairs);
    }

    public function map(string $name): ?array { return $this->maps[strtolower($name)]??null; }
    public function coreValues(): array { return $this->rates; }
    public function monsterByMapContext(int $monMapId,string $mapName): ?array
    { $map=$this->map($mapName);if(!$map)return null;$row=$this->mapMonsterRows[(int)$map['id']][$monMapId]??null;if(!$row)return null;return $this->monsters[(int)$row['MonsterID']]??null; }

    public function mapMonsters(int $mapId): array
    {
        $rows=[];foreach($this->mapMonsterRows[$mapId]??[] as $mm){$mon=$this->monsters[(int)$mm['MonsterID']]??null;if($mon)$rows[]=array_merge($mon,$mm);}$out=[];
        foreach($rows as $r){
            $id=(int)$r['MonMapID'];
            $x=(array_key_exists('X',$r)&&$r['X']!==null&&$r['X']!=='')?(float)$r['X']:null;
            $y=(array_key_exists('Y',$r)&&$r['Y']!==null&&$r['Y']!=='')?(float)$r['Y']:null;
            $out[$id]=[
                'MonID'=>(int)$r['MonsterID'],'MonMapID'=>$id,'Frame'=>(string)$r['Frame'],'Aggresive'=>(int)$r['Aggresive'],
                'X'=>$x,'Y'=>$y,'DBPosition'=>($x!==null&&$y!==null),
                'Name'=>(string)$r['Name'],'File'=>(string)$r['File'],'Linkage'=>(string)$r['Linkage'],'Level'=>(int)$r['Level'],
                'HP'=>(int)$r['Health'],'HPMax'=>(int)$r['Health'],'MP'=>(int)$r['Mana'],'MPMax'=>(int)$r['Mana'],'DPS'=>(int)$r['DPS'],
                'Respawn'=>(int)$r['Respawn'],'Speed'=>(int)$r['Speed'],'DamageReduction'=>(float)$r['DamageReduction'],'Immune'=>(int)$r['Immune'],
                'state'=>1,'targets'=>[],'auras'=>[],'dots'=>[],'skills'=>$this->monsterSkills[(int)$r['MonsterID']]??[],'skillCooldowns'=>[],'lastCombat'=>0.0,'lastRegen'=>microtime(true),'lastAttack'=>0.0,'respawnAt'=>0.0,
            ];
        }
        return $out;
    }


    /** @return array{npcBranch:array,npcdef:array,npcmap:array} */
    public function mapNpcPayload(int $mapId): array
    {
        $branch=[];$defs=[];$placements=[];$seenDefs=[];
        foreach($this->mapNpcRows[$mapId]??[] as $placement){
            $npcId=(int)($placement['NpcID']??$placement['NPCID']??0);$npcMapId=(int)($placement['NpcMapID']??$placement['id']??0);
            $npc=$this->npcs[$npcId]??null;if(!$npc||$npcMapId<=0)continue;
            $level=max(1,(int)($npc['Level']??1));$hp=max(0,(int)($npc['Health']??0));$mp=max(0,(int)($npc['Mana']??0));$dps=max(0,(int)($npc['DPS']??0));
            $branch[]=['NpcID'=>(string)$npcId,'NpcMapID'=>(string)$npcMapId,'bRed'=>'0','iLvl'=>$level,'intHP'=>$hp,'intHPMax'=>$hp,'intMP'=>$mp,'intMPMax'=>$mp,'intState'=>1,'wDPS'=>$dps];
            if(!isset($seenDefs[$npcId])){$defs[]=['NpcID'=>(string)$npcId,'intHP'=>$hp,'intHPMax'=>$hp,'intLevel'=>$level,'intMP'=>$mp,'intMPMax'=>$mp,'strBehave'=>'walk'];$seenDefs[$npcId]=true;}
            $eqp=$this->npcEquipment($npc);$buttons=[];
            foreach($this->npcButtons[$npcId]??[] as $b)$buttons[]=['strAction'=>(string)($b['Action']??''),'strText'=>(string)($b['Text']??''),'strValue'=>(string)($b['Value']??''),'strIcon'=>(string)($b['Icon']??'')];
            $placements[]=[
                'strUsername'=>(string)($npc['Name']??('NPC '.$npcId)),'NpcID'=>(string)$npcId,'NpcMapID'=>(string)$npcMapId,
                'strFrame'=>(string)($placement['Frame']??'Enter'),'X'=>(float)($placement['X']??0),'Y'=>(float)($placement['Y']??0),
                'State'=>'Stop','Animation'=>'Idle','strDialog'=>(string)($npc['Slogan']??''),'strJob'=>(string)($npc['Job']??''),
                'strTurn'=>(string)($placement['Turn']??'Right'),'strGender'=>$this->npcGender((string)($npc['Gender']??'M')),
                'intColorHair'=>$this->npcColor($npc['ColorHair']??null,'0x000000'),'intColorEye'=>$this->npcColor($npc['ColorEye']??null,'0x000000'),
                'intColorSkin'=>$this->npcColor($npc['ColorSkin']??null,'0xE2C3A3'),'intColorBase'=>$this->npcColor($npc['ColorBase']??null,'0x000000'),
                'intColorAccessory'=>$this->npcColor($npc['ColorAccessory']??null,'0x000000'),'intColorTrim'=>$this->npcColor($npc['ColorTrim']??null,'0x000000'),
                // Optional static-image appearance. Blank keeps the legacy SWF/equipment avatar.
                'strImage'=>trim((string)($npc['Image']??'')),
                // Send both keys so current/older Aera client builds can resolve the image path.
                'Image'=>trim((string)($npc['Image']??'')),
                'ImageScale'=>(float)($npc['ImageScale']??1.0),
                'ImageOffsetX'=>(float)($npc['ImageOffsetX']??0.0),
                'ImageOffsetY'=>(float)($npc['ImageOffsetY']??0.0),
                'eqp'=>$eqp,'buttons'=>$buttons,
            ];
        }
        return ['npcBranch'=>$branch,'npcdef'=>$defs,'npcmap'=>$placements];
    }

    /** Database-driven transition arrows for one source map. */
    public function mapArrowPayload(int $mapId): array
    {
        $out=[];
        foreach($this->mapArrowRows[$mapId]??[] as $row){
            $targetType=strcasecmp(trim((string)($row['TargetType']??'Room')),'Map')===0?'Map':'Room';
            $targetMapId=(int)($row['TargetMapID']??0);
            if($targetType==='Room'||$targetMapId<=0)$targetMapId=$mapId;
            $targetMap=$this->mapById($targetMapId);
            if($targetType==='Map'&&!$targetMap)continue;
            $direction=trim((string)($row['Direction']??'Right'));
            $allowedDirections=[
                'Right','Slight Down-Right','Down-Right','Steep Down-Right',
                'Down','Steep Down-Left','Down-Left','Slight Down-Left',
                'Left','Slight Up-Left','Up-Left','Steep Up-Left',
                'Up','Steep Up-Right','Up-Right','Slight Up-Right'
            ];
            if(!in_array($direction,$allowedDirections,true))$direction='Right';
            $rotation=null;
            if(array_key_exists('Rotation',$row)&&$row['Rotation']!==null&&$row['Rotation']!==''){
                $rotation=fmod((float)$row['Rotation'],360.0);
                if($rotation<0)$rotation+=360.0;
            }
            $out[]=[
                'ArrowID'=>(int)($row['id']??0),
                'MapID'=>$mapId,
                'strFrame'=>(string)($row['Frame']??'Enter'),
                'X'=>(float)($row['X']??0),
                'Y'=>(float)($row['Y']??0),
                'Direction'=>$direction,
                'Rotation'=>$rotation,
                'TargetType'=>$targetType,
                'TargetMapID'=>$targetMapId,
                'TargetMapName'=>(string)($targetMap['Name']??''),
                'TargetFrame'=>(string)($row['TargetFrame']??'Enter'),
                'TargetPad'=>(string)($row['TargetPad']??'Spawn'),
            ];
        }
        return $out;
    }

    private function mapById(int $id): ?array
    {
        if($id<=0)return null;
        foreach($this->maps as $map)if((int)($map['id']??0)===$id)return $map;
        return null;
    }

    private function npcGender(string $value): string
    { $v=strtoupper(trim($value));return str_starts_with($v,'F')?'F':'M'; }

    private function npcColor(mixed $value,string $default): string
    {
        if($value===null||trim((string)$value)==='')return $default;$v=trim((string)$value);
        if(str_starts_with(strtolower($v),'0x'))return '0x'.strtoupper(substr($v,2));
        if(str_starts_with($v,'#'))return '0x'.strtoupper(substr($v,1));
        if(is_numeric($v))return sprintf('0x%06X',(int)$v & 0xFFFFFF);
        return $default;
    }

    private function npcEquipment(array $npc): array
    {
        $out=[];
        $slots=[['WeaponID','Weapon'],['ArmorID','co'],['HelmID','he'],['CapeID','ba'],['GroundID','mi']];
        foreach($slots as [$field,$fallback]){
            $id=(int)($npc[$field]??0);if($id<=0)continue;$item=$this->items[$id]??null;if(!$item)continue;
            $slot=trim((string)($item['Equipment']??''));
            if($field==='ArmorID'){if(!in_array($slot,['ar','co'],true))$slot=strcasecmp((string)($item['Type']??''),'Class')===0?'ar':'co';}
            elseif($field==='WeaponID')$slot='Weapon';
            elseif(!in_array($slot,['he','ba','mi'],true))$slot=$fallback;
            $out[$slot]=['ItemID'=>$id,'sFile'=>(string)($item['File']??''),'sLink'=>(string)($item['Link']??''),'sType'=>(string)($item['Type']??''),'sMeta'=>(string)($item['Meta']??'')];
        }
        return $out;
    }

    public function randomServerMessage(): ?string
    { if(!$this->serverMessages)return null;$row=$this->serverMessages[array_rand($this->serverMessages)];$m=trim((string)($row['message']??''));return $m===''?null:$m; }

    private function rows(string $sql): array { try{return $this->db->all($sql);}catch(Throwable $e){if($this->log)$this->log->error('World cache query failed: '.$e->getMessage().' | SQL: '.$sql);return [];} }
    private function keyed(string $sql,callable $key): array { $out=[];foreach($this->rows($sql) as $r)$out[$key($r)]=$r;return $out; }
}
